# Q1: Import numpy library

In [83]:
# write your code here ^_^
import numpy as np 

# Q2: Generate a sequence of 15 floats using linspace() function

In [84]:
# write your code here ^_^
x =np.linspace(0,15,15)
x

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [85]:
# write your code here ^_^
arr1 = [1.1,2.1,3.1]
arr2 = [4.1,5.1,6.1]
arr3 = [7.1,8.1,9.1]
arr4 = [10.1,11.1,12.1]
array =np.array([
    [arr1,arr2],[arr3,arr4]
    ])
array.shape

(2, 2, 3)

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [86]:
# write your code here ^_^
print('''
- Array's type. {}
- Array's elements datatype. {}
- Array's shape. {}
- Array's size. {}
- Array's dimention. {}
'''.format(type(array),array.dtype,array.shape,array.size,array.ndim))


- Array's type. <class 'numpy.ndarray'>
- Array's elements datatype. float64
- Array's shape. (2, 2, 3)
- Array's size. 12
- Array's dimention. 3



# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [87]:
# write your code here ^_^
arr1 = [1.1,2.1,3.1]
arr2 = [4.1,5.1,6.1]
arr3 = [7.1,8.1,9.1]
arr4 = [10.1,11.1,12.1]
array4d =np.array([[
    [arr1,arr2],[arr3,arr4]
    ]])
array4d.shape

print('''
- Array's type. {}
- Array's elements datatype. {}
- Array's shape. {}
- Array's size. {}
- Array's dimention. {}
'''.format(type(array4d),array4d.dtype,array4d.shape,array4d.size,array4d.ndim))


- Array's type. <class 'numpy.ndarray'>
- Array's elements datatype. float64
- Array's shape. (1, 2, 2, 3)
- Array's size. 12
- Array's dimention. 4



# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [88]:
# write your code here ^_^
array_int = np.int64(array4d)
array_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [89]:
# write your code here ^_^
for cell in np.nditer(array_int):
    print(cell, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [90]:
# write your code here ^_^
array_int[0,1,0,1]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [91]:
# write your code here ^_^
array_int[0,0,1,1:]

array([5, 6])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [92]:
# write your code here ^_^
np.where(array_int==8)

(array([0]), array([1]), array([0]), array([1]))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [93]:
# write your code here ^_^
array_int.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [94]:
# write your code here ^_^
AR1 = np.array([['A', 'B'], ['E', 'F']])
AR2 = np.array([['C', 'D'], ['G', 'H']])
newarray = np.stack((AR1,AR2))
newarray

array([[['A', 'B'],
        ['E', 'F']],

       [['C', 'D'],
        ['G', 'H']]], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [97]:
# write your code here ^_^
new_array = np.stack((AR1,AR2),axis=1)
new_array

array([[['A', 'B'],
        ['C', 'D']],

       [['E', 'F'],
        ['G', 'H']]], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [102]:
# write your code here ^_^
A1,A2 = np.split(newarray, 2, axis=1)
A1

array([[['A', 'B']],

       [['C', 'D']]], dtype='<U1')